/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acousticfield3d.gui.misc;

import acousticfield3d.gui.MainForm;
import acousticfield3d.scene.Entity;
import acousticfield3d.scene.MeshEntity;
import acousticfield3d.utils.Parse;
import java.util.ArrayList;

/**
 *
 * @author am14010
 */
public class RotateMultipleTimes extends javax.swing.JFrame {
    final MainForm mf;
    
    public RotateMultipleTimes(MainForm mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rxText = new javax.swing.JTextField();
        ryText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rzText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rotatePairsText = new javax.swing.JTextField();
        rotatePairsButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rotateSelectionsText = new javax.swing.JTextField();
        rotateSelectionsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rotate multiple times");

        jLabel1.setText("rx:");

        rxText.setText("0");

        ryText.setText("0");

        jLabel2.setText("ry:");

        rzText.setText("0");

        jLabel3.setText("rz:");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("rotate by pairs:");

        rotatePairsText.setText("0");

        rotatePairsButton.setText("OK");
        rotatePairsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotatePairsButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("rotate selections");

        rotateSelectionsText.setText("0");

        rotateSelectionsButton.setText("OK");
        rotateSelectionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateSelectionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rxText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ryText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rzText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotatePairsText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotatePairsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotateSelectionsText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotateSelectionsButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rzText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rotatePairsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotatePairsButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rotateSelectionsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotateSelectionsButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int rx = Parse.toInt( rxText.getText() );
        int ry = Parse.toInt( ryText.getText() );
        int rz = Parse.toInt( rzText.getText() );
        while (rx > 0 || ry > 0 || rz > 0){
            if (rx>0){
                --rx;
                mf.movePanel.applyRotationOrScale(1, 0, 0);
            }
            if (ry>0){
                --ry;
                mf.movePanel.applyRotationOrScale(0, 1, 0);
            }
            if (rz>0){
                --rz;
                mf.movePanel.applyRotationOrScale(0, 0, 1);
            }
            System.out.println("calc rot " + rx + " " + ry + " " + rz);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void rotatePairsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotatePairsButtonActionPerformed
        final int steps = Parse.toInt( rotatePairsText.getText());
        
        final ArrayList<Entity> points = mf.selection;
        final int n = points.size();
        
        for(int i = 0; i < steps; ++i){
           mf.movePanel.setGenerateKeyFrame(false);
           mf.movePanel.setCalculate(false); //leave in auto for slower but smoother calcs??
           for(int j = 0; j < n/2; ++j){
               final Entity pA = points.get(j*2+0);
               final Entity pB = points.get(j*2+1);
               mf.setSelection(pA);
               mf.addToSelection(pB);
               mf.movePanel.applyRotationOrScale(0, (j%2==0) ? -1 : 1, 0);
           }
           mf.movePanel.setGenerateKeyFrame(true);
           mf.movePanel.setCalculate(true);
           mf.movePanel.applyVector(0, 0, 0);
        }
        
        
        mf.movePanel.setGenerateKeyFrame(true);
        mf.movePanel.setCalculate(true);
    }//GEN-LAST:event_rotatePairsButtonActionPerformed

    private void rotateSelectionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateSelectionsButtonActionPerformed
        final int steps = Parse.toInt( rotateSelectionsText.getText());
        
       final ArrayList<Entity> sel1 = mf.movePanel.getSelection(1);
       final ArrayList<Entity> sel2 = mf.movePanel.getSelection(2);
       
       
        for(int i = 0; i < steps; ++i){
           mf.movePanel.setGenerateKeyFrame(false);
           mf.movePanel.setCalculate(false); //leave in auto for slower but smoother calcs??
           
            mf.setSelection(sel1);
            mf.movePanel.applyRotationOrScale(0, -1, 0);
            mf.setSelection(sel2);
            mf.movePanel.applyRotationOrScale(0,  1, 0);

           mf.movePanel.setGenerateKeyFrame(true);
           mf.movePanel.setCalculate(true);
           mf.movePanel.applyVector(0, 0, 0);
        }
        
        mf.movePanel.setGenerateKeyFrame(true);
        mf.movePanel.setCalculate(true);
    }//GEN-LAST:event_rotateSelectionsButtonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton okButton;
    private javax.swing.JButton rotatePairsButton;
    private javax.swing.JTextField rotatePairsText;
    private javax.swing.JButton rotateSelectionsButton;
    private javax.swing.JTextField rotateSelectionsText;
    private javax.swing.JTextField rxText;
    private javax.swing.JTextField ryText;
    private javax.swing.JTextField rzText;
    // End of variables declaration//GEN-END:variables
}
