/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acousticfield3d.gui.misc;

import acousticfield3d.algorithms.CalcField;
import acousticfield3d.gui.MainForm;
import acousticfield3d.math.M;
import acousticfield3d.math.Vector2f;
import acousticfield3d.math.Vector3f;
import acousticfield3d.scene.MeshEntity;
import acousticfield3d.scene.Resources;
import acousticfield3d.simulation.Transducer;
import acousticfield3d.utils.Color;
import acousticfield3d.utils.Parse;
import java.util.ArrayList;

/**
 *
 * @author am14010
 */
public class TransContributionControl extends javax.swing.JFrame {
    final MainForm mf;
    
    final ArrayList<MeshEntity> lines = new ArrayList<>();
    
    public TransContributionControl(MainForm mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lineThicknessText = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        colorGainText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alphaGainText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("maximum thickness:");

        lineThicknessText.setText("0.3");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("color gain:");

        colorGainText.setText("2500");

        jLabel3.setText("alpha gain:");

        alphaGainText.setText("2500");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lineThicknessText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorGainText))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alphaGainText)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lineThicknessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(colorGainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(alphaGainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(createButton)
                    .addComponent(deleteButton))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        deleteButtonActionPerformed(null);
        
        final int nTrans = mf.simulation.transducers.size();
        final int nPoints = mf.simulation.controlPoints.size();
        final int nLines = nTrans * nPoints;
        for (int i = 0; i < nLines; ++i){
            final MeshEntity me = new MeshEntity(Resources.MESH_BOX, null, Resources.SHADER_SOLID_SPEC);
            me.getTransform().setScale(0);
            lines.add(me);
            mf.scene.getEntities().add(me);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    public void updateLines(){
        final int nTrans = mf.simulation.transducers.size();
        final int nPoints = mf.simulation.controlPoints.size();
        final int nLines = lines.size();
        final float thickness = Parse.toFloat( lineThicknessText.getText() );
        final float colorGain = Parse.toFloat( colorGainText.getText() );
        final float alphaGain = Parse.toFloat( alphaGainText.getText() );
        
        int index = 0;
        for( int t = 0 ; t < nTrans; ++t){
            final Transducer trans = mf.simulation.transducers.get( t );
            for( int p = 0; p < nPoints; ++p){
                final MeshEntity point = mf.simulation.controlPoints.get(p);
                if (index < nLines){
                    final MeshEntity line = lines.get(index);
                    final Vector3f pointPos = point.getTransform().getTranslation();
                    
                    //total the field at the point
                    final Vector2f field = CalcField.calcFieldAt(pointPos, mf);
                    //field generate by the transducer at the point
                    final Vector2f fieldT = CalcField.calcFieldForTrans(trans, trans.getPhase() * M.PI, pointPos.x, pointPos.y, pointPos.z, mf);
                    
                    //calculate the contribution from the transducer
                    final float fieldLength = field.length();
                    //final float fieldTLength = fieldT.length();
                    final float contribution = fieldT.dot( field ) / fieldLength / fieldLength;
                    
                    line.setColor( Gradients.get().getGradientAmp(contribution * colorGain) );
                    final int alpha = (int) (256.0f * ( M.clamp(contribution * alphaGain, 0, 1) ));
                    //line.setColor( Color.changeAlpha(line.getColor(), alpha));
                    
                    //update the line
                    line.getTransform().connectTwoPoints(trans.getTransform().getTranslation(), pointPos, 
                            thickness* contribution);
                    
                }else{
                    return;
                }
                index++;
            }
        }
    }
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateLines();
        mf.needUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        mf.scene.getEntities().removeAll( lines );
        lines.clear();
        mf.needUpdate();
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alphaGainText;
    private javax.swing.JTextField colorGainText;
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lineThicknessText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
