package acousticfield3d.gui.panels;

import acousticfield3d.gui.MainForm;
import acousticfield3d.math.M;
import acousticfield3d.math.Vector3f;
import acousticfield3d.scene.Entity;
import acousticfield3d.scene.MeshEntity;
import acousticfield3d.scene.Resources;
import acousticfield3d.scene.Scene;
import acousticfield3d.simulation.ControlPoint;
import acousticfield3d.simulation.Transducer;
import acousticfield3d.utils.Color;
import acousticfield3d.utils.Parse;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Asier
 */
public class ControlPointPanel extends javax.swing.JPanel {
    public MainForm mf;
    final ArrayList<MeshEntity> groundLines = new ArrayList<>();
    
    public ControlPointPanel(MainForm mf) {
        this.mf = mf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        cpEnableCheck = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        cpSizeText = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        cpColorText = new javax.swing.JTextField();
        cpAddButton = new javax.swing.JButton();
        cpDelButton = new javax.swing.JButton();
        placeBeadAtSliceCheck = new javax.swing.JCheckBox();
        selectAllButton = new javax.swing.JButton();
        gridWText = new javax.swing.JTextField();
        gridHText = new javax.swing.JTextField();
        gridAddButton = new javax.swing.JButton();
        groundLineCheck = new javax.swing.JCheckBox();
        lineThicknessText = new javax.swing.JTextField();
        delAutoSendCheck = new javax.swing.JCheckBox();

        jButton3.setText("jButton3");

        cpEnableCheck.setText("enable");
        cpEnableCheck.setToolTipText("enables/disables the control points");
        cpEnableCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpEnableCheckActionPerformed(evt);
            }
        });

        jLabel41.setText("size:");

        cpSizeText.setText("0.0015");
        cpSizeText.setToolTipText("size of the created control points");
        cpSizeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpSizeTextActionPerformed(evt);
            }
        });

        jLabel43.setText("Color:");

        cpColorText.setText("255,255,255,255");
        cpColorText.setToolTipText("color RGBA");
        cpColorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpColorTextActionPerformed(evt);
            }
        });

        cpAddButton.setText("+");
        cpAddButton.setToolTipText("add control point");
        cpAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpAddButtonActionPerformed(evt);
            }
        });

        cpDelButton.setText("-");
        cpDelButton.setToolTipText("delete control point");
        cpDelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpDelButtonActionPerformed(evt);
            }
        });

        placeBeadAtSliceCheck.setText("PlaceBeadAtSlice");
        placeBeadAtSliceCheck.setToolTipText("when cliking on a slice it will add a control point there");

        selectAllButton.setText("Select All");
        selectAllButton.setToolTipText("select all the control points");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        gridWText.setText("4");

        gridHText.setText("3");

        gridAddButton.setText("gridAdd");
        gridAddButton.setToolTipText("adds a grid of particles");
        gridAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridAddButtonActionPerformed(evt);
            }
        });

        groundLineCheck.setText("lines");
        groundLineCheck.setToolTipText("adds ground lines of the specified thickness");
        groundLineCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groundLineCheckActionPerformed(evt);
            }
        });

        lineThicknessText.setText("0.00025");

        delAutoSendCheck.setText("send");
        delAutoSendCheck.setToolTipText("auto calc and send when deleting a point");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cpEnableCheck)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpSizeText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(7, 7, 7)
                        .addComponent(cpColorText))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gridWText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gridHText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gridAddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(groundLineCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineThicknessText))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(placeBeadAtSliceCheck, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectAllButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cpAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(cpDelButton)
                                .addGap(18, 18, 18)
                                .addComponent(delAutoSendCheck)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpEnableCheck)
                    .addComponent(jLabel41)
                    .addComponent(cpSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(cpColorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpDelButton)
                    .addComponent(delAutoSendCheck))
                .addGap(18, 18, 18)
                .addComponent(selectAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(placeBeadAtSliceCheck)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gridWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gridHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gridAddButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groundLineCheck)
                    .addComponent(lineThicknessText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public ControlPoint addControlPoint(final float x, final float y, final float z){
        ControlPoint me = new ControlPoint(Resources.MESH_SPHERE, null, Resources.SHADER_SOLID_SPEC);
        
        me.setTag( Entity.TAG_CONTROL_POINT );
     
        me.setColor( Color.parse( getControlPointColor() ) );
        me.getTransform().getScale().set( getControlPointSize() );
        me.getTransform().getTranslation().set(x, y, z);

        mf.scene.getEntities().add(me);
        mf.simulation.controlPoints.add(me);
        
        return me;
    }
    
   
    private void cpEnableCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpEnableCheckActionPerformed
        Scene.setVisible( mf.scene.getEntities(), Entity.TAG_CONTROL_POINT, cpEnableCheck.isSelected());
        mf.needUpdate();
    }//GEN-LAST:event_cpEnableCheckActionPerformed

    private void cpSizeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpSizeTextActionPerformed
        final float size = getControlPointSize();
        for (Entity e : mf.selection){
            if (e.getTag() == Entity.TAG_CONTROL_POINT ){
                e.getTransform().getScale().set( size );
            }
        }
        mf.needUpdate();
    }//GEN-LAST:event_cpSizeTextActionPerformed

    private void cpColorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpColorTextActionPerformed
        final int color = Color.parse( getControlPointColor() );
        for (Entity e : mf.selection){
            if (e.getTag() == Entity.TAG_CONTROL_POINT && (e instanceof MeshEntity)){
                MeshEntity me = (MeshEntity)e;
                me.setColor( color );
            }
        }
        mf.needUpdate();
    }//GEN-LAST:event_cpColorTextActionPerformed

    private void cpAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpAddButtonActionPerformed
        Vector3f sCenter = mf.simulation.getSimulationCenter();
        addControlPoint (sCenter.x, sCenter.y, sCenter.z);
        mf.needUpdate();
    }//GEN-LAST:event_cpAddButtonActionPerformed

    public boolean isClickAndPlace(){
        return placeBeadAtSliceCheck.isSelected();
    }
    
    private void cpDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpDelButtonActionPerformed
        //Remove from simulation and scene
        for (Entity e : mf.selection){
            if (e.getTag() == Entity.TAG_CONTROL_POINT){
                mf.scene.getEntities().remove( e );
                mf.simulation.controlPoints.remove( e );
            }
        }
        mf.clearSelection();
        
        if (delAutoSendCheck.isSelected()){
            selectAll();
            mf.movePanel.applyDisplacement(0, 0, 0);
        }
        
        mf.needUpdate();
    }//GEN-LAST:event_cpDelButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        selectAll();
        mf.needUpdate();
    }//GEN-LAST:event_selectAllButtonActionPerformed

    public ControlPoint addControlPoint(final Vector3f pos){
        return addControlPoint(pos.x, pos.y, pos.z);
    }
    
    
    private void gridAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridAddButtonActionPerformed
        final int w = Parse.toInt( gridWText.getText() );
        final int h = Parse.toInt( gridHText.getText() );
        final Vector3f sCenter = mf.simulation.getSimulationCenter();
        final Vector3f simSize = mf.simulation.getSimulationSize();
       
        final float sepW = simSize.x / (w+1);
        final float sepH = simSize.z / (h+1);
        
        
        for( int ix = 0; ix < w; ++ix){
            for (int iy = 0; iy < h; ++iy){
                
                addControlPoint (
                        sCenter.x - simSize.x/2 + sepW + sepW*ix, 
                        sCenter.y, 
                        sCenter.z - simSize.z/2 + sepH + sepH*iy);
            }
        }
       mf.needUpdate();
    }//GEN-LAST:event_gridAddButtonActionPerformed

    private void groundLineCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groundLineCheckActionPerformed
        if (groundLineCheck.isSelected()){
           final int nPoints = mf.simulation.controlPoints.size();
           for (int i = 0; i < nPoints; ++i){
               final MeshEntity line = new MeshEntity(Resources.MESH_BOX, null, Resources.SHADER_SOLID_SPEC);
               line.setTag( Entity.TAG_GROUND_LINE );
               groundLines.add(line);
               mf.scene.getEntities().add(line);
            }
            updateGroundLines();
            mf.needUpdate();
        }else{
            groundLines.clear();
            mf.scene.removeWithTag(Entity.TAG_GROUND_LINE );
            mf.needUpdate();
        }
    }//GEN-LAST:event_groundLineCheckActionPerformed


    public void updateGroundLines(){
        final int nLines =  groundLines.size();
        final int nPoints = mf.simulation.controlPoints.size();
        final int n = M.min(nLines, nPoints);
        final float thickness = Parse.toFloat( lineThicknessText.getText() );
        final float minY = mf.simulation.getBoundaryMin().y;
        
        final Vector3f tmp = new Vector3f();
        for (int i = 0; i < n; ++i){
            final Vector3f pos = mf.simulation.controlPoints.get(i).getTransform().getTranslation();
            final MeshEntity line = groundLines.get(i);
            tmp.set(pos).y = minY;
            
            line.getTransform().connectTwoPoints(pos, tmp, thickness);
        }
        
    }
    
    public boolean isGroundLineSelected(){
        return groundLineCheck.isSelected();
    }
    
    public void selectAll() {
        mf.clearSelection();
        for(MeshEntity me : mf.scene.getEntities()){
            if ( (me.getTag() & Entity.TAG_CONTROL_POINT) != 0){
                me.selected = true;
                mf.selection.add(me);
            }
        }
       
    }
    
    public Entity selectFrame(int frame) {
        mf.clearSelection();
        for(MeshEntity me : mf.scene.getEntities()){
            if ( (me.getTag() & Entity.TAG_CONTROL_POINT) != 0 ){
                me.selected = true;
                mf.selection.add(me);
            }
        }
        if (mf.selection.isEmpty()){
            return null;
        }else{
            return mf.selection.get(0);
        }
    }
    
    public void setOnlyCurrentCPsVisible(int number){
        Scene.setVisible( mf.scene.getEntities() , Entity.TAG_CONTROL_POINT, true);
    }
    
    public String getControlPointColor(){
        return cpColorText.getText();
    }
    
   
    public float getControlPointSize(){
        return Parse.toFloat( cpSizeText.getText() );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cpAddButton;
    private javax.swing.JTextField cpColorText;
    private javax.swing.JButton cpDelButton;
    private javax.swing.JCheckBox cpEnableCheck;
    private javax.swing.JTextField cpSizeText;
    private javax.swing.JCheckBox delAutoSendCheck;
    private javax.swing.JButton gridAddButton;
    private javax.swing.JTextField gridHText;
    private javax.swing.JTextField gridWText;
    private javax.swing.JCheckBox groundLineCheck;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JTextField lineThicknessText;
    private javax.swing.JCheckBox placeBeadAtSliceCheck;
    private javax.swing.JButton selectAllButton;
    // End of variables declaration//GEN-END:variables

    public void createPoints(int n) {
        final Vector3f sCenter = mf.simulation.getSimulationCenter();
        for (int i = 0; i < n; ++i) {
            addControlPoint(sCenter.x, sCenter.y, sCenter.z);
        }
    
    }

    public void deleteAllPoints() {
        mf.scene.getEntities().removeAll(mf.simulation.controlPoints);
        mf.simulation.controlPoints.clear();
    }

    public void addPoints(ArrayList<ControlPoint> allPoints) {
        mf.scene.getEntities().addAll( allPoints );
        mf.simulation.controlPoints.addAll( allPoints );
    }

    public void mergeClosestPoint() {
        final Entity currentPoint = mf.movePanel.getBeadEntity();
        if (currentPoint == null) { return;}
        
        float minDist = Float.MAX_VALUE;
        Entity entity = null;
        for ( MeshEntity p : mf.simulation.controlPoints){
            if (p != currentPoint){
                final float dist = p.getTransform().getTranslation().distance( currentPoint.getTransform().getTranslation());
                if (dist < minDist){
                    minDist = dist;
                    entity = p;
                }
            }
        }
        if (entity != null){
            currentPoint.getTransform().getTranslation().addLocal( entity.getTransform().getTranslation()).divideLocal(2);
            mf.scene.getEntities().remove( entity );
            mf.simulation.controlPoints.remove( entity );
            mf.selection.remove(entity);
            mf.movePanel.applyDisplacement(0, 0, 0);
        }
    }

    public void deletePoints(ArrayList<MeshEntity> toRemove) {
        mf.scene.getEntities().removeAll( toRemove );
        mf.simulation.controlPoints.removeAll(toRemove);
    }


    
}
